[pytest]

addopts =
    -v
    -s
    --html=report.html
    --self-contained-html

testpaths = .

python_files = test_*.py

python_functions = test_*

log_cli = true
log_cli_level = INFO

markers =
    smoke: smoke tests
    regression: regression tests
    install: installation tests
	feature: feature tests